### ISSUE TITLE
Can I use srsUE to connect to a real eNodeB?

### ISSUE THREAD

**Issue by relentless-warrior** [srsLTE/srsUE#11]
Can I use srsUE installed on USRP B210 to connect to a network provider's eNodeB, i.e., a real eNodeB deployed by the carriers, e.g., T-Mobile, AT&T and so on?

**Comment by ismagom** [comment]
Hi, 

yes it can, but you would need a license to transmit in a licensed LTE band. We have tested it in our labs using cables and the UE has successfully established stable IP sessions with commercial eNodeB.

**Comment by relentless-warrior** [comment]
What type of antenna did you use with USRP board?
